# **Task 13 - (Article 80 to 85)** [![Static Badge](https://img.shields.io/badge/Open%20in%20Colab%20-%20orange?style=plastic&logo=googlecolab&labelColor=grey)](https://colab.research.google.com/github/sshrizvi/DS-Python/blob/main/Numpy/Tasks/task_13.ipynb)

|🔴 **WARNING** 🔴|
|:-----------:|
|If you have not studied article 80 to 85. Do checkout the articles before attempting the task.|
| Here is [Article 80 - NumPy - An Introduction](../Articles/80_numpy.md) |

**Note** : In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.

### 📦 **Importing NumPy Library**

In [2]:
import numpy as np

### 🎯 **Q1: Create a Null Vector with a Specific Value at the Fifth Position**

1. **Problem Statement**:  
   You are tasked with creating a NumPy array (vector) of size 10, where all elements are initialized to zero, except for the fifth element which should be set to 1.

2. **Input Format**:
   - No specific input is required from the user. You need to initialize the vector directly.

3. **Output Format**:
   - The output should be a NumPy array of size 10, where:
     - The first 4 elements are `0`.
     - The fifth element is `1`.
     - The remaining elements (6th to 10th) are `0`.

4. **Example**:

   - **Example 1**:
     Output:
     ```bash
     [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
     ```

   - In this case, the array contains 10 elements, with the fifth element being `1`, and the rest are zeros.

In [2]:
# Solution - Question 01

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 🎯 **Q2: Generate a Random Array and Compute Its Average**

1. **Problem Statement**:  
   Write a program that:
   - Asks the user to input two integers `a` and `b`.
   - Generates a random NumPy array of shape `(a, b)`, where `a` is the number of rows and `b` is the number of columns.
   - Prints the generated array.
   - Computes and prints the average of all the elements in the array.

2. **Input Format**:
   - The program should ask the user to input two integers, `a` (number of rows) and `b` (number of columns).

3. **Output Format**:
   - The output should display:
     - The generated random array of shape `(a, b)`.
     - The average of all the elements in the array.

4. **Example**:

   - **Example 1**:
     - Input:
       ```bash
       a = 3
       b = 4
       ```
     - Output:
       ```bash
       Array:
       [[0.22741378 0.6091361  0.9464184  0.3823055 ]
        [0.72340594 0.37607643 0.34828162 0.14423899]
        [0.10271749 0.25435264 0.28998455 0.05816926]]

       Average: 0.3821461494171348
       ```

   - In this case, the program generates a 3x4 array with random values, and then computes and prints the average of all elements in the array.

In [5]:
# Solution - Question 02

a = int(input('Enter value of a : '))
b = int(input('Enter value of b : '))

array = np.random.random((a,b))
average_of_array = np.mean(array)

print(array)
print(f'Average of Array is {average_of_array}')

[[0.09233823 0.18293797 0.10792227]
 [0.30645031 0.55564392 0.92525521]
 [0.97200382 0.31608908 0.1896433 ]
 [0.82446563 0.08633677 0.5511754 ]
 [0.70842485 0.88685931 0.79185046]]
Average of Array is 0.4998264357818635


### 🎯 **Q3: Create a 2D Matrix with Border of 1's and Inner Elements as 0's**

1. **Problem Statement**:  
   Write a function that:
   - Accepts two integers `a` and `b` as parameters, which represent the number of rows (`a`) and columns (`b`) for a 2D matrix.
   - The function should generate a 2D array (matrix) where the border elements are `1` and all the inner elements are `0`. The matrix should have the shape `(a, b)`.

2. **Input Format**:
   - The function takes two integers `a` and `b` as input, where `a` is the number of rows and `b` is the number of columns.

3. **Output Format**:
   - The function should return a 2D NumPy array (matrix) where:
     - The border elements are `1`.
     - The inner elements are `0`.

4. **Example**:

   - **Example 1**:
     - Input:  
       ```python
       a = 4
       b = 4
       ```
     - Output:
       ```python
       [[1 1 1 1]
        [1 0 0 1]
        [1 0 0 1]
        [1 1 1 1]]
       ```

   - **Example 2**:
     - Input:  
       ```python
       a = 5
       b = 6
       ```
     - Output:
       ```python
       [[1 1 1 1 1 1]
        [1 0 0 0 0 1]
        [1 0 0 0 0 1]
        [1 0 0 0 0 1]
        [1 1 1 1 1 1]]
       ```

In [9]:
# Solution - Question 03

def create_matrix(a, b):
    array = np.zeros((a, b), dtype=int)
    for i in range(a):
        for j in range(b):
            if i == 0 or i == (a-1) or j == 0 or j == (b-1):
                array[i][j] = 1
    return array


a = int(input('Enter value of a : '))
b = int(input('Enter value of b : '))
print(create_matrix(a, b))

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


### 🎯 **Q4: Create a Vector of Size 10 with Values Ranging from 0 to 1, Both Excluded**

1. **Problem Statement**:  
   Write a program that:
   - Creates a vector of size 10.
   - The values in the vector should range from 0 to 1, **excluding** both 0 and 1.

2. **Input Format**:
   - There is no specific input required from the user, as the vector size is predefined (size 10) and the range of values is between 0 and 1.

3. **Output Format**:
   - The output should be a NumPy array (vector) of size 10 where the values are randomly generated between 0 and 1, excluding both.

4. **Example**:

   - **Example 1**:
     - Output:  
       ```python
       [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
        0.63636364 0.72727273 0.81818182 0.90909091]
       ```

In [12]:
# Solution - Question 04

size = 10
vector = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 🎯 **Q5: Can You Create an Identity Matrix of Shape (3,4)? If Yes, Write Code for It**

1. **Problem Statement**:  
   Write a program to create an identity matrix. The identity matrix is a square matrix with ones on the main diagonal and zeros elsewhere. However, the matrix shape provided is **(3, 4)**, which is not square.

2. **Task**:  
   - You need to create a matrix of shape **(3, 4)**, but the matrix cannot be a true identity matrix as the shape is not square.
   - The main diagonal should have ones, but there will be no diagonal element for the fourth column as it is not possible to have a square identity matrix with 3 rows and 4 columns.

3. **Output Format**:
   - The output should be a NumPy matrix with shape **(3, 4)**, with ones on the diagonal and zeros elsewhere.

4. **Example**:

   - **Example 1**:
     - Input:  
       `shape = (3, 4)`
     - Output:  
       ```python
       [[1. 0. 0. 0.]
        [0. 1. 0. 0.]
        [0. 0. 1. 0.]]
       ```

In [17]:
# Solution - Question 05

identity_matrix = np.eye(3)
identity_matrix_extended = np.hstack((identity_matrix, np.zeros((3, 1))))
print(identity_matrix_extended)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### 🎯 **Q6: Create a 5x5 Matrix with Row Values Ranging from 0 to 4**

1. **Problem Statement**:  
   Write a program to create a 5x5 matrix where each row contains values ranging from **0 to 4**.

2. **Task**:  
   - The matrix should have **5 rows** and **5 columns**.
   - Each row should contain the values starting from **0** to **4**, i.e., each row will have a sequence of numbers from 0 to 4.
   - The matrix should be populated with these values across all rows.

3. **Output Format**:
   - The output should be a 5x5 NumPy array where each row contains values from 0 to 4.

4. **Example**:

   - **Example 1**:
     - Input:  
       `shape = (5, 5)`
     - Output:  
       ```python
       [[0 1 2 3 4]
        [0 1 2 3 4]
        [0 1 2 3 4]
        [0 1 2 3 4]
        [0 1 2 3 4]]
       ```

In [111]:
# Solution - Question 06

row = np.arange(0,5,1)
matrix = np.array(np.tile(row, 5).reshape(5,5))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 🎯 **Q7: Calculate Distances from a Given Point**

1. **Problem Statement**:  
   - Create a random integer vector with shape `(10, 2)`, where each row represents a coordinate in a 2D space. The integers should range from 1 to 100.  
   - A specific 2D coordinate point is given as:  
     ```python
     point = np.array([2, 3])
     ```
   - Calculate the distance of each coordinate in the random vector from the given point. The distances should be stored in an array of integer type.  

2. **Input**:  
   - A random vector of shape `(10, 2)` with integer values between 1 and 100.  
   - A specific point as `np.array([2, 3])`.  

3. **Output**:  
   - An integer array containing the distance of each coordinate in the random vector from the given point.  

4. **Example** (Illustrative):  
   - **Random Vector**:  
     ```
     [[5, 10], [2, 2], [15, 25], ..., [8, 9]]
     ```  
   - **Given Point**:  
     ```
     [2, 3]
     ```  
   - **Distance Array**:  
     ```
     [7, 1, 28, ..., 10]
     ```  

In [38]:
# Solution - Question 07

def calculate_distance(point_vector, point):
    for i in point_vector:
        yield ((i[0] - point[0])**2 + (i[1] - point[1])**2)**0.5

point = np.array([2, 3])
point_vector = (np.random.random((10,2))*100).astype(int)
distance_generator = calculate_distance(point_vector, point)
distance_vector = np.zeros((10,))
index = 0
for i in distance_generator:
    distance_vector[index] = i
    index = index + 1

print(distance_vector.astype(int)) # Values may vary as points are randomly generated

[ 82  74  50  88  79  41  96 109  71  81]


### 🎯 **Q8: Determine the Index of a Specific Element in a Multidimensional Array**

1. **Problem Statement**:  
   - You are given a multidimensional array with the shape `(6, 7, 8)` representing three dimensions:  
     - `x` with a size of 6,  
     - `y` with a size of 7,  
     - `z` with a size of 8.  
   - Determine the **index (x, y, z)** of the 100th element in this array, assuming **zero-based indexing**.  

2. **Relevant Information**:  
   - The array elements are stored in a **row-major order** (C-style indexing).  
   - The counting starts at the **first element of the array** (index `(0, 0, 0)`).  

3. **Input**:  
   - Array shape: `(6, 7, 8)`  
   - Element position to find: `100` (zero-based indexing applies).  

4. **Output**:  
   - The index `(x, y, z)` corresponding to the 100th element of the array.  

In [4]:
# Solution - Question 08

count = 1
for i in range(6):
    for j in range(7):
        for k in range(8):
            if count == 100:
                print(f'({i},{j},{k})')
                count = count + 1
                break
            count = count + 1

(1,5,3)


### 🎯 **Q9: Reverse a NumPy Array with Float Type**

1. **Problem Statement**:  
   - You are given a single line of input containing a space-separated list of numbers.  
   - Your task is to reverse the sequence of numbers and output the result as a NumPy array with the data type `float`.  

2. **Relevant Information**:  
   - Convert the input numbers into a NumPy array.  
   - The resulting array must have elements in reverse order compared to the input.  
   - The data type of the elements in the array should be `float`.  

3. **Input Format**:  
   - A single line of input containing space-separated numbers.  

4. **Output Format**:  
   - A single line containing the reversed NumPy array with `float` data type.  

5. **Example**:  

   **Input**:  
   ```bash
   1 2 3 4 -8 -10
   ```  

   **Output**:  
   ```bash
   [-10.  -8.   4.   3.   2.   1.]
   ```

In [7]:
# Solution - Question 09

data = input('Enter space-separated numbers : ')
l = data.split()
array = np.array(l[::-1], dtype=float)
print(array)

[-10.  -8.   4.   3.   2.   1.]


### 🎯 **Q10: Count the Number of Elements in a NumPy Array**

1. **Problem Statement**:  
   - You are given a NumPy array.  
   - Your task is to count the total number of elements in the array and display the result.

2. **Relevant Information**:  
   - The NumPy array can be empty or non-empty.  
   - The output should indicate the total number of elements present in the array.

3. **Input Format**:  
   - A single NumPy array.  

4. **Output Format**:  
   - A single line of output displaying the total count of elements in the array with the format:  
     `elements_count : <count>`  

5. **Examples**:  

   **Example 1**:  
   **Input**:  
   ```bash
   np.array([])
   ```  
   **Output**:  
   ```bash
   elements_count :  0
   ```  

   **Example 2**:  
   **Input**:  
   ```bash
   np.array([1, 2])
   ```  
   **Output**:  
   ```bash
   elements_count :  2
   ```  

In [10]:
# Solution - Question 10

array = np.array([1, 2])
print('elements_count :', array.size)

elements_count : 2


### 🎯 **Q11: Implement the Softmax Function**

1. **Problem Statement**:  
   - Write a Python function to calculate the **Softmax** of a given 1D NumPy array.  
   - The function must validate the input to ensure it is a NumPy 1D array.  
   - If the input is not a valid 1D NumPy array, raise an appropriate error.

2. **Formula**:  
   The Softmax function is defined as:  
   $$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$  
   Here, \(z\) is the input array, and the output is the normalized exponential distribution.

3. **Input Format**:  
   - A NumPy 1D array.

4. **Output Format**:  
   - A NumPy 1D array containing the Softmax values for each element of the input array.

5. **Error Handling**:  
   - Raise an error if the input is not a NumPy 1D array.

6. **Examples**:  

   **Example 1**:  
   **Input**:  
   ```bash
   [86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318]
   ```  
   **Output**:  
   ```bash
   [2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
          5.05514197e-22, 1.50974911e-22]
   ```  

   **Example 2**:  
   **Input**:  
   ```bash
   [33.17344305, 45.61961654, 82.05405781, 80.9647098, 68.82830233, 91.52064278]
   ```  
   **Output**:  
   ```bash
   [4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
          1.39571531e-10, 9.99896577e-01]
   ```

In [11]:
# Solution - Question 11

def softmax(array):
    if array.ndim != 1:
        raise ValueError('Array provided is not one-dimensional :(')
    exponential_array = np.exp(array)
    softmax_array = exponential_array / np.sum(exponential_array)
    return softmax_array

array = np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])
print(softmax(array))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### 🎯 **Q12: Vertical Stack Function**

1. **Problem Statement**:  
   - Write a Python function that accepts an **infinite number of NumPy arrays** as input arguments and performs a **vertical stack** operation on them.  
   - The function must validate that all inputs are NumPy arrays.  
   - If any input is not a valid NumPy array, raise an appropriate error.  

2. **Requirements**:  
   - The resulting array should contain all the input arrays stacked vertically.  
   - Ensure the function handles arrays of compatible shapes for stacking.  

3. **Input Format**:  
   - Any number of NumPy arrays as input arguments.  

4. **Output Format**:  
   - A single NumPy array representing the vertical stack of all input arrays.  

5. **Error Handling**:  
   - Raise an error if any input is not a valid NumPy array.  

6. **Examples**:  

   **Example 1**:  
   **Input**:  
   ```bash
   a = [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]
   
   b = [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]
   ```  
   **Output**:  
   ```bash
   [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1]]
   ```  

   **Example 2**:  
   **Input**:  
   ```bash
   a = [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]
   
   b = [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]
   
   c = [[0.10117373, 0.1677244, 0.73764059, 0.83166097, 0.48985695],
        [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]]
   ```  
   **Output**:  
   ```bash
   [[0.         1.         2.         3.         4.        ],
    [5.         6.         7.         8.         9.        ],
    [1.         1.         1.         1.         1.        ],
    [1.         1.         1.         1.         1.        ],
    [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695],
    [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
   ```

In [13]:
# Solution - Question 12

def vertical_stacker(*args):
    for array in args:
        if isinstance(array, np.ndarray):
            pass
        else:
            raise TypeError('Array provided is not an ndarray :(')
    return np.vstack(args)
         

a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])
   
b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

c = np.array([[0.10117373, 0.1677244, 0.73764059, 0.83166097, 0.48985695],
              [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

print(vertical_stacker(a, b, c))

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### 🎯 **Q13: Dates**

1. **Problem Statement**:  
   Write a Python function named **`date_array`** that generates a NumPy array of dates between two specified dates, **inclusive of the start and end dates**.  

2. **Function Requirements**:  
   - The function should accept **exactly two arguments**, both of which must be strings representing the dates.  
   - The date format must strictly follow **YYYY-MM-DD** (e.g., `2022-12-06`).  
   - If the input is not in the required format or if more or fewer arguments are provided, the function should raise an appropriate error.  
   - The range of dates must be from the **same year**.  

3. **Input Format**:  
   - **Start Date**: A string in the format `YYYY-MM-DD`.  
   - **End Date**: A string in the format `YYYY-MM-DD`.  

4. **Output Format**:  
   - A NumPy array containing all dates, starting from the **start date** to the **end date**, inclusive.  

5. **Error Handling**:  
   - Raise an error if the input is not in the required format or if the year of the two dates is different.  

6. **Examples**:  

   **Example 1**:  
   **Input**:  
   ```bash
   date_array(start='2020-09-15', end='2020-09-25')
   ```  
   **Output**:  
   ```bash
   ['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
    '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
    '2020-09-23', '2020-09-24', '2020-09-25']
   ```  

   **Example 2**:  
   **Input**:  
   ```bash
   date_array(start='2022-12-01', end='2022-12-06')
   ```  
   **Output**:  
   ```bash
   ['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', 
    '2022-12-05', '2022-12-06']
   ```  

   **Example 3**:  
   **Input**:  
   ```bash
   date_array(start='2020-11-25', end='2020-11-30')
   ```  
   **Output**:  
   ```bash
   ['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28', 
    '2020-11-29', '2020-11-30']
   ```

In [41]:
# Solution - Question 13

from datetime import *

def date_array(start:str, end:str) -> np.ndarray:
    try:
        start_date = datetime.strptime(start, "%Y-%m-%d")
        end_date = datetime.strptime(end, "%Y-%m-%d")
        dates = []
        while start_date <= end_date:
            dates.append(str(datetime.date(start_date)))
            start_date = start_date + timedelta(days = 1)
        
        return np.array(dates)
    
    except ValueError as e:
        print('\033[1;37;41m ValueError \033[0;37;m', e.args[0].title())

start = '2020-09-15'
end = '2020-09-25'
print(date_array(start, end))

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


### 🎯 **Q14: Subtract Row Mean from a Matrix**

1. **Problem Statement**:  
   Write a program or function that **subtracts the mean of each row** from the respective row in a given matrix. The result should be a matrix of the same dimensions, where each element of a row has been adjusted by subtracting the row's mean.

2. **Input Format**:  
   - A 2D matrix represented as a NumPy array.

3. **Output Format**:  
   - A 2D matrix (NumPy array) where each row has had its mean subtracted.

4. **Constraints**:  
   - The input matrix must be a valid NumPy array with numerical elements.
   - If the matrix is empty, handle appropriately by returning an empty matrix.

5. **Example 1**:  

   **Input**:  
   ```bash
   [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
   ```  

   **Output**:  
   ```bash
   [[-1.  0.  1.]
    [-1.  0.  1.]
    [-1.  0.  1.]]
   ```  

6. **Example 2**:  

   **Input**:  
   ```bash
   [[10, 20, 30],
    [15, 15, 15],
    [1, 5, 10]]
   ```  

   **Output**:  
   ```bash
   [[-10.   0.  10.]
    [  0.   0.   0.]
    [ -4.   0.   5.]]
   ```

In [48]:
# Solution - Question 14

def row_mean_difference_matrix(matrix):
    output_matrix = np.zeros(matrix.shape)
    row_mean_matrix = np.mean(matrix, axis=1)
    row_index = 0
    while row_index < matrix.shape[0]:
        output_matrix[row_index] = matrix[row_index] - row_mean_matrix[row_index]
        row_index += 1
    return output_matrix

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(row_mean_difference_matrix(matrix))

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


### 🎯 **Q15: Swap Columns in a Matrix**

1. **Problem Statement**:  
   Write a program or function to **swap the first column** (column-1) of a 2D matrix with the **second column** (column-2). The resulting matrix should retain its original dimensions with the specified columns exchanged.

2. **Input Format**:  
   - A 2D matrix represented as a NumPy array.  
   - The matrix must have at least two columns.

3. **Output Format**:  
   - A 2D matrix (NumPy array) where column-1 and column-2 have been swapped.

4. **Constraints**:  
   - The input matrix must be a valid NumPy array.  
   - The matrix must have at least two columns; otherwise, raise an error or handle appropriately.

5. **Example 1**:  

   **Input**:  
   ```bash
   [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
   ```  

   **Output**:  
   ```bash
   [[2, 1, 3],
    [5, 4, 6],
    [8, 7, 9]]
   ```  

6. **Example 2**:  

   **Input**:  
   ```bash
   [[10, 20],
    [30, 40],
    [50, 60]]
   ```  

   **Output**:  
   ```bash
   [[20, 10],
    [40, 30],
    [60, 50]]
   ```  

In [51]:
# Solution - Question 15

def swap_columns(matrix):
    if matrix.ndim != 2:
        raise TypeError('Given NumPy Array is not 2D :(')
    if matrix.shape[1] < 2:
        raise TypeError('Given NumPy Array does not have enough columns to swap :(')
    for i in matrix:
        i[0], i[1] = i[1], i[0]

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
swap_columns(matrix)
print(matrix)

[[2 1 3]
 [5 4 6]
 [8 7 9]]


### 🎯 **Q16: Replace Odd Elements in an Array**

1. **Problem Statement**:  
   Write a program or function to **replace all odd elements** in a given NumPy array with the value `-1`. The rest of the elements should remain unchanged.

2. **Input Format**:  
   - A 1D or 2D NumPy array containing integers.  

3. **Output Format**:  
   - A NumPy array of the same dimensions as the input, where all odd elements are replaced with `-1`.

4. **Constraints**:  
   - The input must be a valid NumPy array.  
   - The array can have any number of dimensions (1D, 2D, or higher).  

5. **Example 1**:  

   **Input**:  
   ```bash
   [1, 2, 3, 4, 5]
   ```  

   **Output**:  
   ```bash
   [-1, 2, -1, 4, -1]
   ```  

6. **Example 2**:  

   **Input**:  
   ```bash
   [[1, 6, 3],
    [4, 9, 8]]
   ```  

   **Output**:  
   ```bash
   [[-1, 6, -1],
    [4, -1, 8]]
   ```  

7. **Example 3**:  

   **Input**:  
   ```bash
   [[2, 4],
    [6, 8]]
   ```  

   **Output**:  
   ```bash
   [[2, 4],
    [6, 8]]
   ```

In [56]:
# Solution - Question 16

def replace_odds(a):
    shape = a.shape
    flatten_array = np.ravel(a)
    idx = 0
    while idx < flatten_array.size:
        if flatten_array[idx] % 2 != 0:
            flatten_array[idx] = -1
        idx += 1
    return flatten_array.reshape(shape)
        

a = np.array([[1, 6, 3],
              [4, 9, 8]])
print(replace_odds(a))

[[-1  6 -1]
 [ 4 -1  8]]


### 🎯 **Q17: Create an Array of Element-Wise Maximum from Two Arrays**

1. **Problem Statement**:  
   Given two NumPy arrays of the same shape, create a new array where each element is the maximum value from the corresponding positions of the two input arrays.

2. **Input Format**:  
   - Two 1D NumPy arrays of the same length.

3. **Output Format**:  
   - A NumPy array of the same shape, where each element is the maximum of the corresponding elements from the two input arrays.

4. **Constraints**:  
   - Both arrays must have the same shape and be valid NumPy arrays.  
   - The values can be integers or floats.

5. **Example 1**:  

   **Input**:  
   ```bash
   a = [6, 3, 1, 5, 8]
   b = [3, 2, 1, 7, 2]
   ```

   **Output**:  
   ```bash
   [6, 3, 1, 7, 8]
   ```

6. **Example 2**:  

   **Input**:  
   ```bash
   a = [1.5, 3.2, 7.8]
   b = [2.1, 2.9, 7.8]
   ```

   **Output**:  
   ```bash
   [2.1, 3.2, 7.8]
   ```

7. **Example 3**:  

   **Input**:  
   ```bash
   a = [9, 0, -1]
   b = [2, 8, 0]
   ```

   **Output**:  
   ```bash
   [9, 8, 0]
   ```

In [60]:
# Solution - Question 17

def max_array(a , b):
    array = np.array([a, b])
    return np.max(array, axis = 0)

a = np.array([6, 3, 1, 5, 8, 2])
b = np.array([3, 2, 1, 7, 2, 5])
print(max_array(a, b))

[6 3 1 7 8 5]


### 🎯 **Q18: Operations on a Given Array**

1. **Problem Statement**:  
   Perform the following operations on a randomly generated 2D NumPy array:

   - Fetch every alternate column of the array.  
   - Normalize the array using the given normalization formula:  
     $$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$  

2. **Input Format**:  
   - A 2D NumPy array with dimensions (8, 5), where elements are random integers in the range [1, 10000].  

   ```python
   arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8, 5)
   ```

3. **Output Format**:  
   - A 2D array containing every alternate column of the original array.  
   - A 2D normalized array with all values scaled between 0 and 1, based on the given formula.

4. **Example Input**:  

   ```bash
   arr1 =
   [[ 1234  5678  9101  2345  6789]
    [ 1235  5679  9102  2346  6790]
    [ 1236  5680  9103  2347  6791]
    [ 1237  5681  9104  2348  6792]
    [ 1238  5682  9105  2349  6793]
    [ 1239  5683  9106  2350  6794]
    [ 1240  5684  9107  2351  6795]
    [ 1241  5685  9108  2352  6796]]
   ```

5. **Example Outputs**:  

   - **For Operation 1** (Every Alternate Column):  

     ```bash
     [[1234 9101 6789]
      [1235 9102 6790]
      [1236 9103 6791]
      [1237 9104 6792]
      [1238 9105 6793]
      [1239 9106 6794]
      [1240 9107 6795]
      [1241 9108 6796]]
     ```

   - **For Operation 2** (Normalized Array):  

     ```bash
     [[0.00000000e+00 5.64389129e-01 9.99110998e-01 1.41097282e-01 7.05486411e-01]
      [1.27000254e-04 5.64516129e-01 9.99237998e-01 1.41224282e-01 7.05613411e-01]
      [2.54000508e-04 5.64643129e-01 9.99364999e-01 1.41351283e-01 7.05740411e-01]
      [3.81000762e-04 5.64770130e-01 9.99491999e-01 1.41478283e-01 7.05867412e-01]
      [5.08001016e-04 5.64897130e-01 9.99618999e-01 1.41605283e-01 7.05994412e-01]
      [6.35001270e-04 5.65024130e-01 9.99745999e-01 1.41732283e-01 7.06121412e-01]
      [7.62001524e-04 5.65151130e-01 9.99873000e-01 1.41859284e-01 7.06248412e-01]
      [8.89001778e-04 5.65278131e-01 1.00000000e+00 1.41986284e-01 7.06375413e-01]]
     ```  



In [97]:
# Solution - Question 18

def operation_1(array):
   return array[:,::2]

def normalization(array):
   min_value = array.min()
   max_value = array.max()
   new_array = (array - min_value) / (max_value - min_value)
   return new_array

arr1 = np.array(
   [[ 1234,  5678,  9101,  2345,  6789],
    [ 1235,  5679,  9102,  2346,  6790],
    [ 1236,  5680,  9103,  2347,  6791],
    [ 1237,  5681,  9104,  2348,  6792],
    [ 1238,  5682,  9105,  2349,  6793],
    [ 1239,  5683,  9106,  2350,  6794],
    [ 1240,  5684,  9107,  2351,  6795],
    [ 1241,  5685,  9108,  2352,  6796]])
print(' Alternate Columns '.center(70, '-'), operation_1(arr1), sep='\n')
print(' Normalized Array '.center(70, '-'), normalization(arr1), sep='\n')


------------------------- Alternate Columns --------------------------
[[1234 9101 6789]
 [1235 9102 6790]
 [1236 9103 6791]
 [1237 9104 6792]
 [1238 9105 6793]
 [1239 9106 6794]
 [1240 9107 6795]
 [1241 9108 6796]]
-------------------------- Normalized Array --------------------------
[[0.00000000e+00 5.64389129e-01 9.99110998e-01 1.41097282e-01
  7.05486411e-01]
 [1.27000254e-04 5.64516129e-01 9.99237998e-01 1.41224282e-01
  7.05613411e-01]
 [2.54000508e-04 5.64643129e-01 9.99364999e-01 1.41351283e-01
  7.05740411e-01]
 [3.81000762e-04 5.64770130e-01 9.99491999e-01 1.41478283e-01
  7.05867412e-01]
 [5.08001016e-04 5.64897130e-01 9.99618999e-01 1.41605283e-01
  7.05994412e-01]
 [6.35001270e-04 5.65024130e-01 9.99745999e-01 1.41732283e-01
  7.06121412e-01]
 [7.62001524e-04 5.65151130e-01 9.99873000e-01 1.41859284e-01
  7.06248412e-01]
 [8.89001778e-04 5.65278131e-01 1.00000000e+00 1.41986284e-01
  7.06375413e-01]]


### 🎯 **Q19: Find the nth Largest Element in a 1D Array**

1. **Problem Statement**:  
   Write a function that accepts two arguments:
   - **First**: A 1D NumPy array `arr`.
   - **Second**: An integer `n`, where `n <= len(arr)`.

   The function should return the **nth largest** element in the array.

2. **Input Format**:
   - A 1D NumPy array `arr` with integer values.
   - An integer `n` where `n` is less than or equal to the length of the array `arr`.

3. **Output Format**:
   - The output should be the `nth` largest item in the array `arr`.

4. **Examples**:

   - **Example 1**:  
     Input:
     ```python
     arr = np.array([12, 34, 40, 7, 1, 0])
     n = 3
     ```
     Output:
     ```bash
     12
     ```

   - **Example 2**:  
     Input:
     ```python
     arr = np.array([12, 34, 40, 7, 1, 0])
     n = 1
     ```
     Output:
     ```bash
     40
     ```  

In [100]:
# Solution - Question 19

def nth_largest(arr, n):
    sorted_array = np.sort(arr, kind='mergesort')
    return sorted_array[-n]

arr = np.array([12, 34, 40, 7, 1, 0])
n = 3
print(nth_largest(arr, n))

12


### 🎯 **Q20: Create a Pattern from a 1D Array**

1. **Problem Statement**:  
   Given a 1D NumPy array `a`, create a pattern as shown below, without hardcoding. Use only NumPy functions to generate the pattern.

2. **Input Format**:
   - A 1D NumPy array `a` containing integer values.
   
3. **Output Format**:
   - The output should be a NumPy array following the given pattern rules.
   
4. **Pattern Explanation**:
   The pattern is formed by repeating each element of the array `a` a number of times equal to its value, and then cycling through the elements of the array in a specific order.

5. **Example**:

   - **Example 1**:  
     Input:
     ```python
     a = np.array([1, 2, 3])
     ```
     Output:
     ```bash
     [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
     ```

   In this case:
   - The element `1` appears 3 times initially.
   - The element `2` appears 3 times next.
   - The element `3` appears 3 times.
   - Then the array repeats the cycle `[1, 2, 3]` multiple times.

In [103]:
# Solution - Question 20

def create_pattern(array):
    return np.ravel(np.array([np.repeat(array, array.size), np.tile(array, array.size)]))

a = np.array([1, 2, 3])
print(create_pattern(a))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
