# **Task 15 - (Article 92 to 95)** [![Static Badge](https://img.shields.io/badge/Open%20in%20Colab%20-%20orange?style=plastic&logo=googlecolab&labelColor=grey)](https://colab.research.google.com/github/sshrizvi/DS-Python/blob/main/Numpy/Tasks/task_15.ipynb)

|🔴 **WARNING** 🔴|
|:-----------:|
|If you have not studied article 92 to 95. Do checkout the articles before attempting the task.|
| Here is [Numpy Tricks : Important Methods - Part One](../Articles/92_numpy_tricks_part1.md) |

### 📦 **Importing NumPy Library**

In [1]:
import numpy as np

### 🎯 **Q1: Create a Random 4x3 Matrix and Perform Sorting Tasks**  

1. **Problem Statement**:  
   Write a program to create a `4x3` matrix with random integer values between 0 and 100. Perform various sorting operations on this matrix as outlined below.  

2. **Inputs**:  
   - A randomly generated matrix of shape `(4, 3)` with integers in the range `[0, 100]`.  

3. **Tasks**:  
   i. **Sort the Matrix Row-wise**:  
      Use the `np.sort()` function to sort the elements in each row of the matrix in ascending order.  

   ii. **Sort Based on Values in the Second Column**:  
       Sort the rows of the matrix based on the values in the second column (column index `1`).  

   iii. **Sort Based on the Maximum Value in Each Row**:  
        Rearrange the rows of the matrix in descending order of the maximum value in each row.  

   iv. **Sort Based on All Elements in Ascending Order**:  
       Flatten the matrix and sort all elements in ascending order, then reshape back into a `4x3` matrix.  

4. **Output Format**:  
   - A matrix for each sorting operation.  

5. **Example**:  

   - Input Matrix:  
     ```bash
     arr = 
     [[92 90 74]
      [ 6 63 93]
      [15 93 96]
      [70 60 48]]
     ```  

   - **Output**:  
     i. Row-wise Sorted:  

        ```bash
        [[74 90 92]
         [ 6 63 93]
         [15 93 96]
         [48 60 70]]
        ```  

     ii. Sorted by Second Column: 

        ```bash
        [[70 60 48]
         [ 6 63 93]
         [92 90 74]
         [15 93 96]]
        ```

     iii. Sorted by Row-wise Max Value (Descending):  

        ```bash
        [[15 93 96]
         [ 6 63 93]
         [92 90 74]
         [70 60 48]]
        ```

     iv. Sorted by All Elements:  

        ```bash
        [[ 6 15 48]
         [60 63 70]
         [74 90 92]
         [93 93 96]]
        ```

6. **Additional Notes**:  
   - Use NumPy for matrix creation and sorting operations.  
   - Ensure the program handles edge cases, such as duplicate values or edge values like `0` and `100`.  

In [39]:
# Solution - Question 01

# Part (i)

arr =  [[92, 90, 74],
        [6 , 63, 93],
        [15, 93, 96],
        [70, 60, 48]]
array = np.array(arr)

print(' Sorted Array '.center(60, '-'))
print()
print(np.sort(array))
print()

# Part (ii)

arr =  [[92, 90, 74],
        [6 , 63, 93],
        [15, 93, 96],
        [70, 60, 48]]
array = np.array(arr)

print(' Sorted by Second Column '.center(60, '-'))
print()
sorted_indices = np.argsort(array[:,1])
print(array[sorted_indices])
print()

# Part (iii)

arr =  [[92, 90, 74],
        [6 , 63, 93],
        [15, 93, 96],
        [70, 60, 48]]
array = np.array(arr)

print(' Sorted by Row-wise Max Value (Descending) '.center(60, '-'))
print()
sorted_indices = np.argsort(np.max(array, axis=1))[::-1]
print(array[sorted_indices])
print()

# Part (iv)

arr =  [[92, 90, 74],
        [6 , 63, 93],
        [15, 93, 96],
        [70, 60, 48]]
array = np.array(arr)

print(' Sorted by All Elements '.center(60, '-'))
print()
print(np.sort(array, axis=None).reshape(array.shape))

----------------------- Sorted Array -----------------------

[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

----------------- Sorted by Second Column ------------------

[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

-------- Sorted by Row-wise Max Value (Descending) ---------

[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

------------------ Sorted by All Elements ------------------

[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]


### 🎯 **Q2: Perform Operations on a Marks Array**  

1. **Problem Statement**:  
   You are provided with an array representing the marks of 5 students in 4 subjects. Perform the following tasks sequentially to modify the array and analyze the data.  

2. **Inputs**:  
   - A 2D array `marks` of shape `(5, 4)` representing marks of 5 students in 4 subjects.  
   - An array `extra_subject` containing the marks of an additional subject for each of the 5 students.  
   - Two additional student records, `rec1` and `rec2`, containing marks for 5 subjects (including the additional subject).  

   Given:  
   ```python
   marks = [[13, 10,  9, 33],
            [63, 46, 90, 42],
            [39, 76, 13, 29],
            [82,  9, 29, 78],
            [67, 61, 59, 36]]

   extra_subject = [41, 87, 72, 36, 92]

   rec1 = [77, 83, 98, 95, 89]
   rec2 = [92, 71, 52, 61, 53]
   ```  

3. **Tasks**:  
   i. **Add Marks for an Additional Subject**:  
      Add the `extra_subject` marks as a fifth column in the `marks` array.  

   ii. **Add Two New Students' Records**:  
       Append the `rec1` and `rec2` records as new rows to the updated `marks` array.  

   iii. **Add a Total Marks Column**:  
        Compute the sum of marks for all 5 subjects for each student and append this as an additional column.  

   iv. **Sort the Array by Total Marks**:  
       Sort the array in descending order based on the total marks column. Display the top 2 rows from this sorted array.  

4. **Output Format**:  
   - Updated array after each task.  
   - Final sorted array and the top 2 rows based on total marks.  

5. **Example**:  

   - **Initial Array**:  
     ```bash
     [[13, 10,  9, 33],
      [63, 46, 90, 42],
      [39, 76, 13, 29],
      [82,  9, 29, 78],
      [67, 61, 59, 36]]
     ```  

   - **After Adding Extra Subject Marks**:  
     ```bash
     [[13, 10,  9, 33, 41],
      [63, 46, 90, 42, 87],
      [39, 76, 13, 29, 72],
      [82,  9, 29, 78, 36],
      [67, 61, 59, 36, 92]]
     ```  

   - **After Adding Two New Students**:  
     ```bash
     [[13, 10,  9, 33, 41],
      [63, 46, 90, 42, 87],
      [39, 76, 13, 29, 72],
      [82,  9, 29, 78, 36],
      [67, 61, 59, 36, 92],
      [77, 83, 98, 95, 89],
      [92, 71, 52, 61, 53]]
     ```  

   - **After Adding Total Marks Column**:  
     ```bash
     [[ 13,  10,   9,  33,  41, 106],
      [ 63,  46,  90,  42,  87, 328],
      [ 39,  76,  13,  29,  72, 229],
      [ 82,   9,  29,  78,  36, 234],
      [ 67,  61,  59,  36,  92, 315],
      [ 77,  83,  98,  95,  89, 442],
      [ 92,  71,  52,  61,  53, 329]]
     ```  

   - **Top 2 Rows Based on Total Marks**:  
     ```bash
     [[ 77,  83,  98,  95,  89, 442],
      [ 92,  71,  52,  61,  53, 329]]
     ```  

6. **Additional Notes**:  
   - Use NumPy functions for matrix manipulations and sorting.  
   - Ensure the code handles different shapes during concatenation or appending.

In [62]:
# Solution - Question 02

marks = np.array([[13, 10,  9, 33],
                  [63, 46, 90, 42],
                  [39, 76, 13, 29],
                  [82,  9, 29, 78],
                  [67, 61, 59, 36]])
extra_subject = np.array([41, 87, 72, 36, 92])
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

print(' Array After Adding Extra Subject Marks '.center(50, '-'))
print()
marks = np.append(marks, np.expand_dims(extra_subject, axis=1), axis=1)
print(marks)
print()

print(' Array After Adding New Records '.center(50, '-'))
print()
marks = np.append(marks, [rec1, rec2], axis=0)
print(marks)
print()

print(' Array After Adding Total Marks '.center(50, '-'))
print()
total_marks = np.sum(marks, axis=1)
new_marks = np.append(marks, np.expand_dims(total_marks, axis=1), axis=1)
print(new_marks)
print()

print(' Records with Maximum Marks '.center(50, '-'))
print()
indices = np.argsort(new_marks[:,-1])
print(new_marks[indices[-1:-3:-1]])

----- Array After Adding Extra Subject Marks -----

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

--------- Array After Adding New Records ---------

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

--------- Array After Adding Total Marks ---------

[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

----------- Records with Maximum Marks -----------

[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


### 🎯 **Q3: Find Unique Arrays Row-Wise and Column-Wise from a 2D Array**

1. **Problem Statement**:  
   You are provided with a 2D array. Your task is to identify and extract the unique rows and unique columns from the array.  

2. **Inputs**:  
   - A 2D NumPy array `arr`.  

   Given:  
   ```python
   arr = np.array([[1, 2, 3, 3, 1, 1],
                   [0, 9, 1, 2, 8, 8],
                   [1, 2, 3, 8, 8, 8],
                   [1, 2, 3, 3, 1, 1]])
   ```  

3. **Tasks**:  
   i. **Find Unique Rows**:  
      Identify and extract all unique rows from the array. The output should be a 2D array containing only unique rows.  

   ii. **Find Unique Columns**:  
       Identify and extract all unique columns from the array. The output should be a 2D array containing only unique columns.  

4. **Output Format**:  
   - A 2D array representing unique rows.  
   - A 2D array representing unique columns.  

5. **Example**:  

   - **Input Array**:  
     ```bash
     [[1, 2, 3, 3, 1, 1],
      [0, 9, 1, 2, 8, 8],
      [1, 2, 3, 8, 8, 8],
      [1, 2, 3, 3, 1, 1]]
     ```  

   - **Unique Rows**:  
     ```bash
     [[0, 9, 1, 2, 8, 8],
      [1, 2, 3, 3, 1, 1],
      [1, 2, 3, 8, 8, 8]]
     ```  

   - **Unique Columns**:  
     ```bash
     [[1, 1, 2, 3, 3],
      [0, 8, 9, 1, 2],
      [1, 8, 2, 3, 8],
      [1, 1, 2, 3, 3]]
     ```  

6. **Additional Notes**:  
   - Utilize NumPy functions for identifying unique elements along specific axes (rows or columns).  
   - Ensure the output maintains the original order of the rows or columns as they appear in the input array.

In [68]:
# Solution - Question 03

arr = np.array([[1, 2, 3, 3, 1, 1],
                [0, 9, 1, 2, 8, 8],
                [1, 2, 3, 8, 8, 8],
                [1, 2, 3, 3, 1, 1]])

print(' Unique Rows '.center(50, '-'))
print(np.unique(arr, axis=0))

print(' Unique Columns '.center(50, '-'))
print(np.unique(arr, axis=1))

------------------ Unique Rows -------------------
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
----------------- Unique Columns -----------------
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


### 🎯 **Q4: Flip a 2D Array Along Both Axes**

1. **Problem Statement**:  
   Given a 2D array, your task is to flip it simultaneously along both the horizontal (row-wise) and vertical (column-wise) axes.

2. **Inputs**:  
   - A 2D NumPy array.

   Example Input:  
   ```python
   arr = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
   ```

3. **Task**:  
   - Flip the array along both axes.  
   - This means the first row becomes the last row, and within each row, the first element becomes the last element.  

4. **Output Format**:  
   - A flipped 2D array that reflects the transformation.

5. **Example**:

   - **Input**:  
     ```bash
     [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]
     ```

   - **Output**:  
     ```bash
     [[9, 8, 7],
      [6, 5, 4],
      [3, 2, 1]]
     ```

6. **Additional Notes**:  
   - Ensure that the flipping operation does not modify the original array (unless explicitly allowed).  
   - Consider using NumPy functions to implement the flipping operation efficiently.  

In [70]:
# Solution - Question 04

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
np.flip(arr, axis=(0,1))

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### 🎯 **Q5: Get Row Numbers of a NumPy Array Having Elements Larger Than X**

1. **Problem Statement**:  
   Write a program to identify and retrieve the row indices of a 2D NumPy array where at least one element in the row is greater than a given value `X`.

2. **Inputs**:  
   - A **2D NumPy array**.  
   - A threshold value `X` (integer).  

   Example Input:  
   ```python
   arr = [[1, 2, 3, 4, 5],
          [10, -3, 30, 4, 5],
          [3, 2, 5, -4, 5],
          [9, 7, 3, 6, 5]]

   X = 6
   ```

3. **Task**:  
   - Identify the row indices where at least one element in the row is greater than `X`.  

4. **Output Format**:  
   - A list or array of row indices satisfying the condition.  

5. **Example**:

   - **Input**:  
     ```bash
     arr = [[1, 2, 3, 4, 5],
            [10, -3, 30, 4, 5],
            [3, 2, 5, -4, 5],
            [9, 7, 3, 6, 5]]

     X = 6
     ```

   - **Output**:  
     ```bash
     [1, 3]
     ```

6. **Additional Notes**:  
   - Ensure your program works for any 2D NumPy array and any integer value of `X`.  
   - Avoid modifying the original array.  
   - Use efficient NumPy operations to identify rows meeting the condition.  

In [73]:
# Solution - Question 05

arr = np.array([[ 1,  2,  3,  4, 5],
                [10, -3, 30,  4, 5],
                [ 3,  2,  5, -4, 5],
                [ 9,  7,  3,  6, 5]])
X = 6
indices = list(np.unique(np.where(arr > X)[0]))
print(indices)

[1, 3]


### 🎯 **Q6: Convert an Array of Arrays into a Flat 1D Array**

1. **Problem Statement**:  
   Write a program to merge multiple arrays (of different lengths) into a single flat 1D array.

2. **Inputs**:  
   - Multiple 1D NumPy arrays of varying sizes.  
   Example:  
   ```python
   arr1 = np.arange(3)     # [0, 1, 2]
   arr2 = np.arange(3, 7)  # [3, 4, 5, 6]
   arr3 = np.arange(7, 10) # [7, 8, 9]
   ```

3. **Task**:  
   - Combine the arrays into one single array.  
   - Ensure the resulting array is flattened into a single 1D structure.

4. **Output Format**:  
   - A single 1D NumPy array.  
   Example Output:  
   ```bash
   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
   ```

5. **Example**:

   - **Input**:  
     ```bash
     arr1 = [0, 1, 2]
     arr2 = [3, 4, 5, 6]
     arr3 = [7, 8, 9]
     ```

   - **Output**:  
     ```bash
     [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
     ```

6. **Additional Notes**:  
   - Ensure your program works for any number of arrays.  
   - Avoid modifying the original arrays.  
   - Use efficient NumPy operations to achieve the task.

In [74]:
# Solution - Question 06

arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

np.ravel(np.concatenate([arr1, arr2, arr3]))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 🎯 **Q7: Find and Remove Minimum and Maximum Elements from an Array**

1. **Problem Statement**:  
   Write a program to find the minimum and maximum elements of a given NumPy array. Once identified, remove these elements from the array.

2. **Inputs**:  
   - A 1D NumPy array containing random integers.  
   Example:  
   ```python
   import numpy as np
   np.random.seed(400)
   arr = np.random.randint(100, 1000, 200).reshape((1, 200))
   ```

3. **Task**:  
   - Identify the **minimum** and **maximum** elements in the array.  
   - Remove these elements from the array while retaining the remaining structure.  
   - If there are duplicates of the minimum or maximum value, remove **only one occurrence** of each.

4. **Output Format**:  
   - A modified NumPy array without the minimum and maximum elements.  

5. **Example**:

   - **Input**:  
     ```bash
     arr = [345, 789, 120, 654, 120, 789]
     ```
   - **Process**:  
     - Minimum = 120  
     - Maximum = 789  
     - Remove one instance of each.  
   - **Output**:  
     ```bash
     [345, 789, 654, 120]
     ```

6. **Additional Notes**:  
   - Ensure the program works efficiently for large arrays.  
   - Use NumPy functions to perform the operations.  
   - The order of elements in the resulting array should remain unchanged except for the removed values.

In [117]:
# Solution - Question 07

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

min_val = np.min(arr)
max_val = np.max(arr)
new_arr = np.delete(arr, np.where(arr == min_val), axis=1)
output = np.delete(new_arr, np.where(new_arr == max_val), axis=1)
output

array([[418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458, 387, 262,
        613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967, 277, 470,
        336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592, 997, 137,
        340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932, 645, 952,
        921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251, 957, 627,
        920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244, 782, 763,
        635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270, 308, 231,
        952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320, 230, 324,
        922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587, 227, 853,
        757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879, 575, 936,
        705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395, 525, 922,
        136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976, 786, 235,
        930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621, 453, 193,
        607, 677, 637, 728, 724, 534, 748, 291, 194

### 🎯 **Q8: Limit Array Elements Between 100 and 200, Sort, and Perform Cumulative Sum**

1. **Problem Statement**:  
   You are given a NumPy array with elements in the range `[100, 700]`. Write a program to:  
   - Restrict the elements of the array such that values **less than 100** are replaced with `100` and values **greater than 200** are replaced with `200`.  
   - Sort the updated array in ascending order.  
   - Compute the cumulative sum of the sorted array.

2. **Inputs**:  
   - A 1D NumPy array with values in the range `[100, 700]`.

3. **Tasks**:  
   - Replace all elements less than `100` with `100` and all elements greater than `200` with `200`.  
   - Sort the resulting array.  
   - Calculate the cumulative sum of the sorted array using `np.cumsum()`.

4. **Output Format**:  
   - The updated array after limiting the values.  
   - The sorted array.  
   - The cumulative sum of the sorted array.

5. **Example**:

   - **Input**:  
     ```bash
     arr = [150, 250, 180, 700, 120, 90, 200, 300]
     ```
   - **Process**:  
     - Limit values: `[150, 200, 180, 200, 120, 100, 200, 200]`  
     - Sort: `[100, 120, 150, 180, 200, 200, 200, 200]`  
     - Cumulative Sum: `[100, 220, 370, 550, 750, 950, 1150, 1350]`  
   - **Output**:  
     ```bash
     Limited Array: [150, 200, 180, 200, 120, 100, 200, 200]
     Sorted Array: [100, 120, 150, 180, 200, 200, 200, 200]
     Cumulative Sum: [100, 220, 370, 550, 750, 950, 1150, 1350]
     ```

6. **Additional Notes**:  
   - Use NumPy functions for efficient manipulation of the array.  
   - Ensure the cumulative sum is displayed as a NumPy array.

In [110]:
# Solution - Question 08

arr = np.array([150, 250, 180, 700, 120, 90, 200, 300])

clipped_array = np.clip(arr, a_min=100, a_max=200)
print(f'Limited Array : {clipped_array}')

sorted_array = np.sort(clipped_array)
print(f'Sorted Array : {sorted_array}')

cumsum_array = np.cumsum(sorted_array)
print(f'Cumulative Sum : {cumsum_array}')

Limited Array : [150 200 180 200 120 100 200 200]
Sorted Array : [100 120 150 180 200 200 200 200]
Cumulative Sum : [ 100  220  370  550  750  950 1150 1350]


### 🎯 **Q9: Analyze Percentiles in a Given Array**

1. **Problem Statement**:  
   You are given a 1D NumPy array with elements in the range `[0, 1]`. Write a program to:  
   - Round off each element of the array to **3 decimal places**.  
   - Verify if the **0th percentile** of the array equals its **minimum value**.  
   - Verify if the **100th percentile** of the array equals its **maximum value**.  
   - Compute the difference between the **51st percentile** and the **50th percentile** values of the array.

2. **Inputs**:  
   - A 1D NumPy array where elements belong to the range `[0, 1]`.

3. **Tasks**:  
   - Round off all elements in the array to 3 decimal places using NumPy.  
   - Find the 0th percentile and verify if it matches the minimum value of the array.  
   - Find the 100th percentile and verify if it matches the maximum value of the array.  
   - Calculate the values at the 50th and 51st percentiles and find their difference.

4. **Output Format**:  
   - Rounded array with elements up to 3 decimal places.  
   - Validation results for:  
     - 0th percentile vs minimum value.  
     - 100th percentile vs maximum value.  
   - The values at the 50th and 51st percentiles.  
   - The difference between the 51st and 50th percentiles.

5. **Example**:

   - **Input**:  
     ```bash
     arr = [0.23456, 0.87564, 0.12345, 0.56789, 0.34567]
     ```
   - **Process**:  
     - Round off: `[0.235, 0.876, 0.123, 0.568, 0.346]`  
     - 0th Percentile: `0.123`, Minimum Value: `0.123` -> Match  
     - 100th Percentile: `0.876`, Maximum Value: `0.876` -> Match  
     - 50th Percentile: `0.346`, 51st Percentile: `0.35488`  
     - Difference: `0.008879999999999999`  

   - **Output**:  
     ```bash
     Rounded Array: [0.235, 0.876, 0.123, 0.568, 0.346]
     0th Percentile Matches Minimum: True
     100th Percentile Matches Maximum: True
     50th Percentile: 0.346, 51st Percentile: 0.35488
     Difference: 0.008879999999999999
     ```

6. **Additional Notes**:  
   - Use NumPy functions like `np.percentile` to compute percentiles.  
   - Ensure that all results are displayed with proper precision.

In [116]:
# Solution - Question 09

arr = np.array([0.23456, 0.87564, 0.12345, 0.56789, 0.34567])

rounded_array = np.round(arr, decimals=3)
print(f'Rounded Array : {rounded_array}')

min_value = np.min(rounded_array)
zeroth_percentile = np.percentile(rounded_array, 0)
print(f'0th Percentile Mathces Minimum: {min_value == zeroth_percentile}')

max_value = np.min(rounded_array)
hundredth_percentile = np.percentile(rounded_array, 0)
print(f'100th Percentile Mathces Maximum: {hundredth_percentile == max_value}')

fifteeth_percentile = np.percentile(rounded_array, 50)
fifty_first_percentile = np.percentile(rounded_array, 51)
print(f'50th Percentile: {fifteeth_percentile}, 51st Percentile: {fifty_first_percentile}')
print(f'Difference: {fifty_first_percentile - fifteeth_percentile}')

Rounded Array : [0.235 0.876 0.123 0.568 0.346]
0th Percentile Mathces Minimum: True
100th Percentile Mathces Maximum: True
50th Percentile: 0.346, 51st Percentile: 0.35488
Difference: 0.008879999999999999
